### PR TITLE
fix: repaired Brinkman query after KB data update

### LINKED ISSUE #58: KB Brinkman gives no results back
KB updated last week an number of LOD datasets including Brinkman. This probably broke the Brinkman query in the catalog. Searching for example for "aardkost" should result in at least http://data.bibliotheken.nl/doc/thes/p075598361 but now comes back empty. Please contact René Voorburg from KB if additional information on the update is required.

### PR DESCRIPTION
**Pull request by sdevalk**
Fix #58.

### CODE REVIEW

**Review by EnnoMeijers — APPROVED** [review]
Looks good! But I did have problems running this query directly on the KB endpoint, I had to replace the FILTER(<bif:contains>... by FILTER(contains( to get results. See also a comment of Kingsley Idehen in https://github.com/openlink/virtuoso-opensource/issues/528 Feels like we really should try to avoid the specific textsearch implementations but this might cause response problems of course.

**Comment by ddeboer** [comment]
Fix #58

**Comment by ddeboer** [comment]
This doesn’t work for me. Is the SPARQL endpoint completely down now?

```bash
comunica-sparql 'http://data.bibliotheken.nl/thes/brinkman/sparql' 'SELECT *  WHERE { ?s ?p ?o}'
[Could not retrieve http://data.bibliotheken.nl/thes/brinkman/sparql (500: unknown error)
Could not retrieve http://data.bibliotheken.nl/thes/brinkman/sparql (500: unknown error)
```

**Comment by EnnoMeijers** [comment]
Note that all the KB datasets are queried on https://data.bibliotheken.nl/sparql and this is up and running. There are no separate endpoints for each dataset.

**Comment by ddeboer** [comment]
Ah yes, of course; my mistake. The query changes work fine on the actual SPARQL endpoint. 😀

**Comment by sdevalk** [comment]
> Looks good! But I did have problems running this query directly on the KB endpoint, I had to replace the FILTER(bif:contains... by FILTER(contains( to get results. See also a comment of Kingsley Idehen in [openlink/virtuoso-opensource#528](https://github.com/openlink/virtuoso-opensource/issues/528) Feels like we really should try to avoid the specific textsearch implementations but this might cause response problems of course.

@EnnoMeijers I've been in touch with René about this. He had to start the full text indexing of Virtuoso manually. I'm now getting the expected results when using `bif:contains`.

Yes, we could replace `bif:contains` with a regular `contains`. Apart from performance issues (but we could test whether this is significant; the Brinkman isn't as large as the NTA), there could be clients that rely on the `bif:contains` functionality (similar to DEVENTit's autocompletion of the NTA), so we'd have to establish this first.

**Pull request merged**
